models/players/ibrahimovic/torso
{
{
map models/players/ibrahimovic/torso
rgbGen lightingDiffuse
}
{
map gfx/effects/torso_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/legs
{
{
map models/players/ibrahimovic/legs
rgbGen lightingDiffuse
}
{
map gfx/effects/legs_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/boots_hips
{
{
map models/players/ibrahimovic/boots_hips
rgbGen lightingDiffuse
}
{
map gfx/effects/boots_hips_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/boots_hipsb
{
{
map models/players/ibrahimovic/boots_hipsb
rgbGen lightingDiffuse
}
{
map gfx/effects/boots_hipsb_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/torso_psg
{
{
map models/players/ibrahimovic/torso_psg
rgbGen lightingDiffuse
}
{
map gfx/effects/torso_psg_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/legs_psg
{
{
map models/players/ibrahimovic/legs_psg
rgbGen lightingDiffuse
}
{
map gfx/effects/legs_psg_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/boots_hips1_psg
{
{
map models/players/ibrahimovic/boots_hips1_psg
rgbGen lightingDiffuse
}
{
map gfx/effects/boots_hips1_psg_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/boots_hipsb_psg
{
{
map models/players/ibrahimovic/boots_hipsb_psg
rgbGen lightingDiffuse
}
{
map gfx/effects/boots_hipsb_psg_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/torso20
{
{
map models/players/ibrahimovic/torso20
rgbGen lightingDiffuse
}
{
map gfx/effects/torso20_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/legs20
{
{
map models/players/ibrahimovic/legs20
rgbGen lightingDiffuse
}
{
map gfx/effects/legs20_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/boots_hips1_20
{
{
map models/players/ibrahimovic/boots_hips1_20
rgbGen lightingDiffuse
}
{
map gfx/effects/boots_hips120_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/ibrahimovic/boots_hipsb_20
{
{
map models/players/ibrahimovic/boots_hipsb_20
rgbGen lightingDiffuse
}
{
map gfx/effects/boots_hipsb20_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}


