models/players/Messi/torso
{
{
map models/players/Messi/torso
rgbGen lightingDiffuse
}
{
map gfx/effects/torso_barca_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/Messi/legs
{
{
map models/players/Messi/legs
rgbGen lightingDiffuse
}
{
map gfx/effects/legs_barca_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/Messi/boots_hips
{
{
map models/players/Messi/boots_hips
rgbGen lightingDiffuse
}
{
map gfx/effects/boots_hips_barca_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/Messi/boots_hips1
{
{
map models/players/Messi/boots_hips1
rgbGen lightingDiffuse
}
{
map gfx/effects/boots_hips1_barca_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}
