models/players/Salah/torso
{
{
map models/players/Salah/torso
rgbGen lightingDiffuse
}
{
map gfx/effects/torso_lfc21_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/Salah/legs
{
{
map models/players/Salah/legs
rgbGen lightingDiffuse
}
{
map gfx/effects/legs_lfc21_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/Salah/boots_hips1
{
{
map models/players/Salah/boots_hips1
rgbGen lightingDiffuse
}
{
map gfx/effects/boots_hips1_lfc21_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}

models/players/Salah/boots_hips
{
{
map models/players/Salah/boots_hips
rgbGen lightingDiffuse
}
{
map gfx/effects/boots_hips_lfc21_glow
blendFunc GL_ONE GL_ONE
glow
rgbGen Identity
}
}
